### ISSUE TITLE
0.7.1 dsi hbmenu download

### ISSUE THREAD

**Issue by Bruhmoment694** [devkitPro/nds-hb-menu#12]
So I am new to the hb scene, but I wanted to download this hb for my ds so I can do more with it. So I was watching a youtuber and I followed his steps and downloaded the first link. But I noticed something weird with it. I saw that the yt video had a packing box symbol by the link, but instead for me it is just a square. Also when I downloaded it, it did not download as a zip and I don't know how to open it. I need to open it to extract the boost.nd file out of it, but without downloading as a zip, I don't know how to extract it. Could you help me find a way to download the link as a zip, or tell me how to extract what I want out of the file it downloaded.

**Comment by Void-Frost** [comment]
7ZIP for Windows should open it.

**Comment by WinterMute** [comment]
We switched to using zip for distribution which should help.
