### ISSUE TITLE
Error : "can't open _dsmenu.dat" on recent R4 card

### ISSUE THREAD

**Issue by dedesite** [devkitPro/nds-hb-menu#14]
Hello,
I just bough a recent R4 card which is labelled with this website : http://www.r4isdhc.com.cn/

I tried to run the hb-menu on it so I format a sd card and copy all the data from the 0.7.1 release and got this error while trying to boot "can't open _dsmenu.dat".

I tried to rename `_DS_MENU.DAT` to `_DSMENU.DAT` but got the same result.

I read in the bootstrap doc that the file might be wrongly encrypted, but which file ? How can I rebuild everything with the good encryption ? Maybe the "new" R4 cards has a different encryption scheme ?

Also, I tried to run the hb menu from the native R4 firmware but `fatInitDefault` failed, do you have an idea why ?

Thanks,
Andréas

**Comment by dedesite** [comment]
For information, I tried to build a new `_DSMENU.DAT` with a file named `r4isd.dldi` found on the website mentioned above, but got the same error.

Here is the makefile target I created :

```Makefile
_DSMENU.DAT	:	$(TARGET).nds r4isd.dldi
	@dlditool r4isd.dldi $<
	@r4denc $< $@
```

Do you have any idea on what else should I try ?

**Comment by SiliconExarch** [comment]
As far as I know the .com.cn cards are part of the R4iLS family of clones so you might want to refer to this: https://github.com/lifehackerhansol/flashcard-bootstrap/blob/217e02b091f61e2c6ae0e1a1a34f59bdcc632520/Makefile#L113

**Comment by anyzunstudios** [comment]
@dedesite  If you R4 has a folder called "_rpg", inside of it there's a *.dldi patch that can be used with dldi patcher.

I'm not 100% sure, but after compiling the _DSMENU.DAT, you have to use r4dec.exe to decrypt the file, so in the output there'll be a "_DSMENU.DAT.DEC" file. 

Then you need to patch the "_DSMENU.DAT.DEC" with DLDI Patcher. Copy the *.dldi file that it's inside the "_rpg" folder and paste it next to the DLDI Patcher. If does not shows, you can manually select the folder  where the *.dldi patch file is.

Once patched, move rename the "_DSMENU.DAT.DEC" to "_DSMENU.DAT" (or whatever is originally called on you card). Be sure that the uppercases and lowercases are like on your original firmware file, and try to boot your R4 again.

One trick to test if that works if to try to run the "_DSMENU.DAT.DEC" once is patched with melonDS emulator. If it runs and says FAT init error, then should work on your R4.

Hope it helps.

Greetings!

**Comment by WinterMute** [comment]
> Can somebody explain me why are you deleting my comments?

They're not useful and have no bearing on the issue.

**Comment by WinterMute** [comment]
@dedesite try the files in this zip.
[test.zip](https://github.com/devkitPro/nds-hb-menu/files/12479769/test.zip)

**Comment by dedesite** [comment]
Hi, sorry for not answering this issue before, but got some help on Discord an finally get it to work.

I can't find right now the solution in my Makefile, but did found the topic on discord :

```Makefile
R4iLS/_DSMENU.DAT    :    $(TARGET).nds r4tfv2.dldi
    @[ -d R4iLS ] || mkdir -p R4iLS
    ndstool    -h 0x200 -c _DSMENU.nds -g "####" "##" "R4XX" -7 $(TARGET).arm7.elf -9 $(TARGET).arm9.elf
    @dlditool ace3ds_sd.dldi _DSMENU.nds 
    r4denc --key 0x4002 _DSMENU.nds $@
    rm _DSMENU.nds
```

This should work.

**Comment by WinterMute** [comment]
> Hi, sorry for not answering this issue before, but got some help on Discord an finally get it to work.
> 
> I can't find right now the solution in my Makefile, but did found the topic on discord :
> 
> ```makefile
> R4iLS/_DSMENU.DAT    :    $(TARGET).nds r4tfv2.dldi
>     @[ -d R4iLS ] || mkdir -p R4iLS
>     ndstool    -h 0x200 -c _DSMENU.nds -g "####" "##" "R4XX" -7 $(TARGET).arm7.elf -9 $(TARGET).arm9.elf
>     @dlditool ace3ds_sd.dldi _DSMENU.nds 
>     r4denc --key 0x4002 _DSMENU.nds $@
>     rm _DSMENU.nds
> ```
> 
> This should work.

I know it works. I wrote it ...

https://github.com/devkitPro/nds-hb-menu/commit/2cbca328bda84099aa54502cc94b04fb951dd164

**Comment by dedesite** [comment]
So it's nice, tank you ;)
