### ISSUE TITLE
make_cia is not an official devKitPro tool

### ISSUE THREAD

**Issue by ahezard** [devkitPro/nds-hb-menu#3]
That prevents nds-hbmenu to build properly : 
make_cia --srl=bootstrap.dsi
make[1]: make_cia: Command not found
make[1]: *** [bootstrap.cia] Error 127
make[1]: Leaving directory `/e/Dev/nds-hb-menu/BootStrap'
"make": *** [BootStrap] Error 2

It would be good to include it into the official sdk

**Comment by WinterMute** [comment]
The provenance of the available tools to create CIAs is rather dubious at best which means that we can't include any of these due to legal concerns.

There is some work in progress to produce untainted tools for this purpose.
