### ISSUE TITLE
there is no boot.nds file?

### ISSUE THREAD

**Issue by AlanPlayz1200** [devkitPro/nds-hb-menu#9]
I am trying to use the menu, but there is no boot.nds file when downloading?

**Comment by Multimegamander** [comment]
Yes there is, open the tarball lol. Can this be closed?

**Comment by jbirm** [comment]
You need to open the bbmenu-0.7.x.tar.bz2 file with a zip reader. The NDS file is located in: 
\\hbmenu-0.7.1.tar.bz2\hbmenu-0.7.1.tar\hbmenu\

**Comment by AlanPlayz1200** [comment]
Thanks
